services:
  books_api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - config.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
