name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: reliable-sol-469016-t0
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build Docker image
        run: |
          gcloud builds submit --tag gcr.io/reliable-sol-469016-t0/books-api:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy books-api \
            --image gcr.io/reliable-sol-469016-t0/books-api:latest \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated
