name: Test GCP Auth

on:
  push:
    branches: [main]

jobs:
  auth-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with GCP
        run: |
          printf '%s' "${{ secrets.GCP_SA_KEY }}" > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project reliable-sol-469016-t0

      - name: Check GCP project
        run: gcloud config list
